language: node_js
node_js:
- '4.5'
before_script:
- npm install
script:
- npm run test-single-run
after_success:
- npm run coveralls
deploy:
  provider: heroku
  api_key:
    secure: vF5+hM8hNIvKSqQzpoBAqebpR/eLW881+nypQ4Aw+lYNXeSzlGqgRgzJWlKxGvuQB5ai8gUfoKz2PX/k7SVJHNHwhJRKdVgIVJMyD5TksN2RTwMZeIoOlwItQuHRHEtI9h9wTMNE+8zVS3whDG9Gk2clW4ahx9uRkw+BxL488SA4SeWLtlIxLshrvFyP05PbRym2l4sex0+lYc33DXkw+mi6wFSNJRuagZoDdi5PZQmfm/P/U+IH/OdLx8uQBDhsC4AoeOO3Z3KB13wdm+vbOmW9ipV/Uxn2rTovQUjcwP7K6T+QeYxlXjbIj9hyE+I4NxyVCIE5B1THOxzf13mSNA7jgTXLLnRriOmhQt9DPfQQjdJlD123esTxu5U2S0TZlawiNSJ1Z0Pwb7hrf7pO3axlhQ5fTgB+ToOKJBeFvjmBfveuOKxqaGiZRYtCSZDgjMu511pOOqJ3ROD5veCRUFJN64faZ7NYybspf+bFLJjBPMZRMulyCQoDWL9F0UYJYzTGswTsKWWL5dc0gyuKl5a58SRwPU86RjmfjAJh+Lt44lo5Ec1YBCfeoD3Ug3/QOgDlawGGk8YI+Rq/cat2AKQ9rfMaVoWpzhV9aEdXdEJbUiaA8G7yv594d7KP2XfDbz8i/O/ouXAm8sFCNhfK4HCHB2PnsqdgfX1VzXeDLqg=
  app: refactored-happiness
  on:
    repo: piorot/refactored-happiness
  run: 
    
